#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase -noZero

rm -rf 0 logs
rm -rf system/domain*
rm -rf postprocess/plots
rm -rf constant/domain*
rm configuration/geometry/mesh.msh
