#!/bin/bash
cd ${0%/*} || exit 1

./Allclean

# Source run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

blockMesh

topoSet

for domain in $(foamListRegions); do
    # Create folder if it doesn't exist
    mkdir -p system/$domain
    mkdir -p constant/$domain

    cp constant/properties constant/$domain/properties

    # Copy fvSchemes and fvSolution
    cp system/fvSchemes system/$domain/fvSchemes
    cp system/fvSolution system/$domain/fvSolution

    # Update 'location' entry in fvSchemes
    sed -i 's@#include[[:space:]]*"\.\./@#include "../../@' system/$domain/fvSchemes
    sed -i 's@#include[[:space:]]*"\.\./@#include "../../@' system/$domain/fvSolution
    foamDictionary system/$domain/fvSchemes -entry "FoamFile/location" -set "\"system/$domain\""
    foamDictionary system/$domain/fvSolution -entry "FoamFile/location" -set "\"system/$domain\""

    sed -i 's@#include "../@#include "../../@' constant/$domain/properties
    # Extract domain number (e.g. domain1 -> 1, domain2 -> 2)
    # Replace epsilonR → epsilonR<domain>
    sed -i "s/epsilonR/epsilonR${domain}/g" constant/$domain/properties

    # Update FoamFile/location entry accordingly
    foamDictionary constant/$domain/properties \
        -entry "FoamFile/location" \
        -set "\"constant/$domain\""
done

cp -r 0.orig 0

# Create logs folder
mkdir -p logs

splitMeshRegions -cellZones -overwrite

# Remove redundant files in 0
for region in $(foamListRegions dielectric)
do
    rm -f 0/$region/eCharge
done

for region in $(foamListRegions)
do
    cp etc/changeDictionary.$region system/$region/changeDictionaryDict
    changeDictionary -region $region
done

runApplication $(getApplication)
mv log.* ./logs/

touch case.foam
