#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase -noZero

rm -r 0
rm -r constant/polyMesh
rm system/fvSolution
rm -r logs

rm -r processor*



