#!/usr/bin/env bash
cd ${0%/*} || exit 1

./Allclean

# Source run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

blockMesh

cp -r 0.orig 0

cp system/fvSolution-foam system/fvSolution
# cp system/fvSolution-petsc system/fvSolution

runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructPar
 
mkdir logs
mv log.* logs/

rm -r processor*
