#!/bin/bash

#---------------------------------------------
#  Allwmake script for foamPlasmaToolkit suite
#  Builds all libraries and the solver
#---------------------------------------------

# Set colors
GREEN='\033[1;32m'
NC='\033[0m'

set -e	# Exit on first error

# Move to script directory (in case called from elsewhere)
cd "${0%/*}" || exit 1

# Libraries
echo "Building Libraries..."
echo "-------------------------------------"
echo ""

wmake libso src/constants
./src/bcs/Allwmake
./src/models/Allwmake
wmake libso src/numerics

# Executables
echo ""
echo "-------------------------------------"
echo "Building Executables..."
echo "-------------------------------------"
echo ""

./src/applications/Allwmake


# ThirdParty
echo "Building ThirdParty..."
echo "-------------------------------------"
echo ""

./ThirdParty/Allwmake

echo
echo "-------------------------------------"
echo -e "${GREEN}Build complete.${NC}"
echo "Libraries are in: \$FOAM_USER_LIBBIN ($FOAM_USER_LIBBIN)"
echo "Solvers are in:   \$FOAM_USER_APPBIN ($FOAM_USER_APPBIN)"
echo "-------------------------------------"
