/*---------------------------------------------------------------------------*\
  File: foamPlasmaToolkitConstants.H
  Part of: foamPlasmaToolkit

  Description:
      Aggregated header including all physical constants defined within the
      foamPlasmaToolkit. 

  Namespace:
      Foam::constant

  Copyright (C) 2025 Rention Pasolari
  License: GNU General Public License v3 or later
      See: <http://www.gnu.org/licenses/>.
\*---------------------------------------------------------------------------*/

#ifndef foamPlasmaToolkitConstants_H
#define foamPlasmaToolkitConstants_H

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#include "plasmaConstants.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
