#!/bin/bash
cd ${0%/*} || exit 1

./Allclean

decompDict="-decomposeParDict system/decomposeParDict"

# Source run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

blockMesh

topoSet

for domain in $(foamListRegions); do
    # Create folder if it doesn't exist
    mkdir -p system/$domain
    mkdir -p constant/$domain

    cp constant/properties constant/$domain/properties

    # Copy fvSchemes and fvSolution
    cp system/fvSchemes system/$domain/fvSchemes
    cp system/fvSolution system/$domain/fvSolution

    # Update 'location' entry in fvSchemes
    sed -i 's@#include[[:space:]]*"\.\./@#include "../../@' system/$domain/fvSchemes
    sed -i 's@#include[[:space:]]*"\.\./@#include "../../@' system/$domain/fvSolution
    foamDictionary system/$domain/fvSchemes -entry "FoamFile/location" -set "\"system/$domain\""
    foamDictionary system/$domain/fvSolution -entry "FoamFile/location" -set "\"system/$domain\""

    sed -i 's@#include "../@#include "../../@' constant/$domain/properties
    # Extract domain number (e.g. domain1 -> 1, domain2 -> 2)
    # Replace epsilonR → epsilonR<domain>
    sed -i "s/epsilonR/epsilonR${domain}/g" constant/$domain/properties

    # Update FoamFile/location entry accordingly
    foamDictionary constant/$domain/properties \
        -entry "FoamFile/location" \
        -set "\"constant/$domain\""
done

runApplication $decompDict decomposePar

restore0Dir -processor

runParallel $decompDict splitMeshRegions -cellZones -overwrite

# Create logs folder
mkdir -p logs

# Remove redundant files in 0
for region in $(foamListRegions dielectric)
do
    rm -f processor*/0/$region/eCharge
done

for region in $(foamListRegions)
do
    cp etc/changeDictionary.$region system/$region/changeDictionaryDict
    runParallel $decompDict -s $region changeDictionary -region $region
done

runParallel $(getApplication)

# Reconstruct
for region in $(foamListRegions)
do
    runParallel -s reconstruct-$region \
        redistributePar -reconstruct -region $region
done

mv log.* ./logs/

for p in processor*
do
    touch $p/$p.foam
done

touch case.foam

# # # for domain in domain1 domain2; do
# # #     foamToVTK -region $domain -noPointValues -time 1
# # #     mv VTK/$domain/*.vtk VTK/$domain/file.vtk
# # # done
