#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase -noZero

rm -r 0

rm -r logs
  
rm configuration/geometry/mesh.msh

for region in $(foamListRegions)
do
    rm -rf system/$region
    rm -rf constant/$region
done


