/*---------------------------------------------------------------------------*\
  File: createFields.H
  Part of: foamPlasmaToolkit
  Developed using the OpenFOAM framework and linked against OpenFOAM libraries.

  Description:
      Derived from createFields.H in OpenFOAM v2412.
      Defines and initializes fields for each region.

  Copyright (C) 2025 Rention Pasolari
  License: GNU General Public License v3 or later
      See: <http://www.gnu.org/licenses/>.
\*---------------------------------------------------------------------------*/

#include "createGasFields.H"
#include "createDielectricFields.H"
