#!/usr/bin/env bash
cd ${0%/*} || exit 1

./Allclean

# Source run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm configuration/geometry/mesh.msh

python ./configuration/geometry/mesh.py

gmshToFoam ./configuration/geometry/mesh.msh

sed -i '/physicalType[[:space:]]*patch;/d' constant/polyMesh/boundary

sed -i '/^[[:space:]]*\(front\|back\)[[:space:]]*$/,/}/ s/^\([[:space:]]*type\)[[:space:]]*.*/\1\t\tempty;/' constant/polyMesh/boundary

for domain in $(foamListRegions); do
    # Create folder if it doesn't exist
    mkdir -p system/$domain
    mkdir -p constant/$domain

    cp constant/electricProperties constant/$domain/electricProperties

    # Copy fvSchemes and fvSolution
    cp system/fvSchemes system/$domain/fvSchemes
    cp system/fvSolution system/$domain/fvSolution

    # Update 'location' entry in fvSchemes
    sed -i 's@#include[[:space:]]*"\.\./@#include "../../@' system/$domain/fvSchemes
    sed -i 's@#include[[:space:]]*"\.\./@#include "../../@' system/$domain/fvSolution
    sed -i "s|location *\".*\"|location\t\"system/$domain\"|" system/$domain/fvSchemes
    sed -i "s|location *\".*\"|location\t\"system/$domain\"|" system/$domain/fvSolution

    sed -i 's@#include "../@#include "../../@' constant/$domain/electricProperties
    sed -i "s|location *\".*\"|location\t\t\"constant/$domain\"|" constant/$domain/electricProperties

    sed -i "s/epsilonR/epsilonR${domain}/g" constant/$domain/electricProperties
done

cp -r 0.orig 0

# Create logs folder
mkdir -p logs

splitMeshRegions -cellZones -overwrite

# Remove redundant files in 0
for region in $(foamListRegions dielectric)
do
    rm -f 0/$region/eCharge
done

for region in $(foamListRegions)
do
    cp etc/changeDictionary.$region system/$region/changeDictionaryDict
    changeDictionary -region $region

    for field in eCharge surfCharge ePotential
    do
        file="0/$region/$field"

        # Make sure the field file actually exists before editing it
        if [ -f "$file" ]; then

            # Only add include if it's NOT already present
            if ! grep -q '#include.*/configuration/config' "$file"; then
                sed -i '/^\/\/ \* \* \* \*/a #include        "../../configuration/config"' "$file"
            fi

        fi
    done
done

runApplication $(getApplication)
mv log.$(getApplication) log.$(getApplication).serial

touch case.foam

mv log.* ./logs/

grep "ExecutionTime" logs/log.$(getApplication).serial | tail -n1


